# Patch para o comandalivre
apiVersion: v1
kind: Service
metadata:
  name: comandalivre-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
# Patch para o Company
apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
---
# Patch para o User
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30082
---
# Patch para o PrumoDigital
apiVersion: v1
kind: Service
metadata:
  name: prumodigital-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30083
---
# Patch para o API Gateway
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30084
---

# Patch para o MailHog
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: http
      port: 8025
      targetPort: 8025
      nodePort: 30025
    - name: smtp
      port: 1025
      targetPort: 1025
      nodePort: 30010

---
# Patch para o Postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30432

---
# Patch para o keycloak
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090

---
# Patch para o Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300

---
# Patch para o OpenTelemetry Collector
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: comandalivre
spec:
  type: NodePort
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30437
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 30438
    - name: metrics
      port: 8889
      targetPort: 8889