apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: comandalivre
type: Opaque
stringData:
  DB_USER: "comanda_livre"
  DB_PASS: "password"
  MINIO_USER: "admin"
  MINIO_PASS: "password"
  KC_ADMIN: "admin"
  KC_PASS: "admin"
  AWS_ACCESS_KEY: "admin"
  AWS_SECRET_KEY: "password"
  MAIL_USERNAME: "no-reply@comandalivre.local"
  MAIL_PASSWORD: ""
  DEFAULT_ADMIN_EMAILS: "pedro.marinho238@gmail.com, pedroermarinho@gmail.com"